# theme.toml template for a Hugo theme
# See https://github.com/spf13/hugoThemes#themetoml for an example

name = "HugoDEB"
license = "MIT"
licenselink = "https://github.com/yourname/yourtheme/blob/master/LICENSE.md"
description = "Hugo theme with Materializecss"
homepage = "http://siteforthistheme.com/"
tags = ["Materializecss"]
features = ["", ""]
min_version = 0.1

[author]
  name = "Benjamin Deplechin"
  homepage = "https://benjamin.deplechin.fr"